# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
---
include:
  - board: nice_nano_v2
    shield: enki42_left
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: enki42_right
    artifact-name: corne_right
  - board: nice_nano_v2
    shield: enki42_dongle dongle_display
    artifact-name: corne_dongle
  - board: nice_nano_v2
    shield: enki42_central_left
    artifact-name: corne_central_left
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset
